{
 "title": "Azure / Insights / Storage Accounts",
 "description": "A dashboard that provides a unified view of Azure Storage services performance, capacity, and availability metrics.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "sub", "label": "Subscription", "query": "subscriptions()" },
   { "name": "ns", "label": "Namespace", "query": "${VAR_NS}" },
   { "name": "rg", "label": "Resource Group", "query": "ResourceGroups($sub)" },
   { "name": "resource", "label": "Resource", "query": "ResourceNames($sub, $rg, $ns)" }
  ]
 },
 "panels": [
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Availability",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Transactions",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "PT5M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "SuccessE2ELatency",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "SuccessServerLatency",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Ingress",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Egress",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Avg Availability for grafanatestraman",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 3 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Minimum",
       "Maximum",
       "Average",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "Availability (Average)",
      "metricDefinition": "microsoft.storage/storageaccounts",
      "metricName": "Availability",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resourceGroup": "ocio-ede-dev-moderate-hl7-rg",
      "resourceName": "grafanatestraman",
      "timeGrain": "auto"
     },
     "subscription": "01f9b1b1-a130-4031-ba25-71771007d3ca"
    }
   ]
  },
  {
   "title": "Transactions by API Name",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       {
        "dimension": "ApiName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Transactions",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Sum_Transactions_SG ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Minimum",
       "Maximum",
       "Average",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Transactions (Total)",
      "metricDefinition": "microsoft.storage/storageaccounts",
      "metricName": "Transactions",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resourceGroup": "ocio-ede-dev-moderate-hl7-rg",
      "resourceName": "grafanatestraman",
      "timeGrain": "auto"
     },
     "subscription": "01f9b1b1-a130-4031-ba25-71771007d3ca"
    }
   ]
  },
  {
   "title": "Availability by storage type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Table availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Availability",
      "metricNamespace": "microsoft.storage/storageaccounts/tableservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/tableServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Blob availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Availability",
      "metricNamespace": "microsoft.storage/storageaccounts/blobservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/blobServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "File availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" },
       { "text": "File Share", "value": "FileShare" }
      ],
      "metricName": "Availability",
      "metricNamespace": "microsoft.storage/storageaccounts/fileservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/fileServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Queue availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Availability",
      "metricNamespace": "microsoft.storage/storageaccounts/queueservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/queueServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Transactions by storage type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "Table transactions",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Transactions",
      "metricNamespace": "microsoft.storage/storageaccounts/tableservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/tableServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "Blob transactions",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Transactions",
      "metricNamespace": "microsoft.storage/storageaccounts/blobservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/blobServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "File transactions",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" },
       { "text": "File Share", "value": "FileShare" }
      ],
      "metricName": "Transactions",
      "metricNamespace": "microsoft.storage/storageaccounts/fileservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/fileServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "Queue transactions",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Transactions",
      "metricNamespace": "microsoft.storage/storageaccounts/queueservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/queueServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Capacity by storage type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Table capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricName": "TableCapacity",
      "metricNamespace": "microsoft.storage/storageaccounts/tableservices",
      "resourceGroup": "select",
      "resourceName": "select",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/tableServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Blob capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Blob type", "value": "BlobType" },
       { "text": "Blob tier", "value": "Tier" }
      ],
      "metricName": "BlobCapacity",
      "metricNamespace": "microsoft.storage/storageaccounts/blobservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/blobServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "File capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "File Share", "value": "FileShare" }
      ],
      "metricName": "FileCapacity",
      "metricNamespace": "microsoft.storage/storageaccounts/fileservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/fileServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Queue capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricName": "QueueCapacity",
      "metricNamespace": "microsoft.storage/storageaccounts/queueservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/queueServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "File Services",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       {
        "dimension": "ApiName",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "ResponseType",
        "filters": [],
        "operator": "eq"
       }
      ],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" },
       { "text": "File Share", "value": "FileShare" }
      ],
      "metricName": "Transactions",
      "metricNamespace": "microsoft.storage/storageaccounts/fileservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/fileServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       {
        "dimension": "ResponseType",
        "filters": [],
        "operator": "eq"
       }
      ],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Transactions",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       {
        "dimension": "ResponseType",
        "filters": [],
        "operator": "eq"
       }
      ],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Transactions",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Blob Services",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       {
        "dimension": "ApiName",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "ResponseType",
        "filters": [],
        "operator": "eq"
       }
      ],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Transactions",
      "metricNamespace": "microsoft.storage/storageaccounts/blobservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/blobServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Table Services",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       {
        "dimension": "ApiName",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "ResponseType",
        "filters": [],
        "operator": "eq"
       }
      ],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Transactions",
      "metricNamespace": "microsoft.storage/storageaccounts/tableservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/tableServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "SuccessE2ELatency",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "SuccessServerLatency",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 53 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "SuccessE2ELatency",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "SuccessServerLatency",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       {
        "dimension": "ApiName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "SuccessE2ELatency",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       {
        "dimension": "ApiName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "SuccessServerLatency",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {}
   ]
  },
  {
   "type": "gauge",
   "description": "The data comes from Storage metrics. It measures the availability of requests on Storage accounts.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Account Availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Availability",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Blob Availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Availability",
      "metricNamespace": "microsoft.storage/storageaccounts/blobservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/blobServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Table Availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Availability",
      "metricNamespace": "microsoft.storage/storageaccounts/tableservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/tableServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "File Availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" },
       { "text": "File Share", "value": "FileShare" }
      ],
      "metricName": "Availability",
      "metricNamespace": "microsoft.storage/storageaccounts/fileservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/fileServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Queue Availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Availability",
      "metricNamespace": "microsoft.storage/storageaccounts/queueservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/queueServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Availability by API name",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       {
        "dimension": "ApiName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Availability",
      "metricNamespace": "microsoft.storage/storageaccounts/blobservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/blobServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       {
        "dimension": "ApiName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Availability",
      "metricNamespace": "microsoft.storage/storageaccounts/tableservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/tableServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       {
        "dimension": "ApiName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" },
       { "text": "File Share", "value": "FileShare" }
      ],
      "metricName": "Availability",
      "metricNamespace": "microsoft.storage/storageaccounts/fileservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/fileServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       {
        "dimension": "ApiName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Availability",
      "metricNamespace": "microsoft.storage/storageaccounts/queueservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/queueServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Availability Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Blob Availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Availability",
      "metricNamespace": "microsoft.storage/storageaccounts/blobservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/blobServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Table Availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Availability",
      "metricNamespace": "microsoft.storage/storageaccounts/tableservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/tableServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "File Availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" },
       { "text": "File Share", "value": "FileShare" }
      ],
      "metricName": "Availability",
      "metricNamespace": "microsoft.storage/storageaccounts/fileservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/fileServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Queue Availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricName": "Availability",
      "metricNamespace": "microsoft.storage/storageaccounts/queueservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/queueServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Account Capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricName": "UsedCapacity",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Blob Capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Blob type", "value": "BlobType" },
       { "text": "Blob tier", "value": "Tier" }
      ],
      "metricName": "BlobCapacity",
      "metricNamespace": "microsoft.storage/storageaccounts/blobservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/blobServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Table Capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricName": "TableCapacity",
      "metricNamespace": "microsoft.storage/storageaccounts/tableservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/tableServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "File Capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "File Share", "value": "FileShare" }
      ],
      "metricName": "FileCapacity",
      "metricNamespace": "microsoft.storage/storageaccounts/fileservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/fileServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Queue Capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricName": "QueueCapacity",
      "metricNamespace": "microsoft.storage/storageaccounts/queueservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/queueServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Storage capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Blob Capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Blob type", "value": "BlobType" },
       { "text": "Blob tier", "value": "Tier" }
      ],
      "metricName": "BlobCapacity",
      "metricNamespace": "microsoft.storage/storageaccounts/blobservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/blobServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Table Capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricName": "TableCapacity",
      "metricNamespace": "microsoft.storage/storageaccounts/tableservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/tableServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "File Capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "File Share", "value": "FileShare" }
      ],
      "metricName": "FileCapacity",
      "metricNamespace": "microsoft.storage/storageaccounts/fileservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/fileServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Queue Capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricName": "QueueCapacity",
      "metricNamespace": "microsoft.storage/storageaccounts/queueservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/queueServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Storage count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Blob Count",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Blob type", "value": "BlobType" },
       { "text": "Blob tier", "value": "Tier" }
      ],
      "metricName": "BlobCount",
      "metricNamespace": "microsoft.storage/storageaccounts/blobservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/blobServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Table Count",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricName": "TableCount",
      "metricNamespace": "microsoft.storage/storageaccounts/tableservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/tableServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "File Count",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "File Share", "value": "FileShare" }
      ],
      "metricName": "FileCount",
      "metricNamespace": "microsoft.storage/storageaccounts/fileservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/fileServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Queue Count",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricName": "FileCount",
      "metricNamespace": "microsoft.storage/storageaccounts/fileservices",
      "resourceGroup": "$rg",
      "resourceName": "$resource/default",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/fileServices/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}