micronaut:
  application:
    name: svc-hl7-validation
  server:
    multipart:
      max-file-size: 10485760
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
  http:
    services:
      redactor:
        urls:
          - ${REDACTOR_URL}
        pool:
          max-concurrent-http1-connections: 50
          enabled: true
          max-connections: 50
      structure:
        urls:
          - ${STRUCTURE_URL}
        pool:
          max-concurrent-http1-connections: 50
          enabled: true
          max-connections: 50

endpoints:
  all:
    enabled: false
    sensitive: true
  loggers:
    write-sensitive: false
  stop:
    enabled: false
  health:
    enabled: true
    details-visible: ANONYMOUS

