micronaut:
  application:
    name: svc-hl7-validation
  server:
    multipart:
      max-file-size: 10485760
    port: 8081
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
  netty:
    event-loops:
      other:
        num-threads: 10
        prefer-native-transport: true
  http:
    client:
      event-loop-group: other
    services:
      redactor:
        urls:
          - ${REDACTOR_URL}
        pool:
          max-concurrent-http1-connections: 50
          enabled: true
          max-connections: 50
      structure:
        urls:
          - ${STRUCTURE_URL}
        pool:
          max-concurrent-http1-connections: 50
          enabled: true
          max-connections: 50
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**

endpoints:
  all:
    enabled: false
    sensitive: true
  loggers:
    write-sensitive: false
  stop:
    enabled: false
  health:
    enabled: true
    details-visible: ANONYMOUS

