name: Publish package to GitHub Packages

on:
  pull_request:
    branches: ['master']
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6

      - name: Publish package
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: publish
          build-root-directory: mrr/
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
