# Fortify code scan required when merging to Main

name: Code Scan Workflow

defaults:
  run:
    shell: bash

on:
  push: 
    branches: [HL7-2957]
  pull_request:
    branches: [HL7-2957]

  workflow_dispatch:
    inputs:
      commitID: 
        default: "BlahBlah"
        type: string
        required: false
      data-exchange-hl7-workflow:
        default: 'pull-request-code-scan.yml'
        type: string
        required: false

  # pull_request:
  #   types: []
  #   branches: [ "HL7-2957" ]
  #   paths: 
  #     - fns-hl7-pipeline/**
  #     # Remaining code bases to be added after above this line are validated.
  #     # 
  #     # - fn-cache-loader/**
  #     # - svc-cloud-transport/**
  #     # - local_libs/**

permissions:
  contents: read
  pull-requests: write # required for `comment-summary-in-pr`
      
jobs:
  invoke-manual-code-scan:
    runs-on: ubuntu-latest
    environment: dev
      
    steps:
    - name: Gen GitHub App Access Token For Manual Trigger
      id: github-app-token
      run: |
        echo ${{ github.workspace }} 
        if [ ! -d data-exchange-hl7 ]; then git clone https://github.com/kave/github-app-token.git; fi;
        sudo tree -df
        cd github-app-token
        sudo gem install jwt
        echo "${{ secrets.CDC_COE_BOTFREY_PEM }}" > app-private-key.pem
        chmod +x ./get-github-app-access-token.sh;
        . ./get-github-app-access-token.sh;
        echo "access_token=${TOKEN}" >> "$GITHUB_ENV"
    - name: Git Commit SHA
      id: getsha
      run: | 
        echo "sha=${{ inputs.commitID }}" >> "$GITHUB_ENV"
    - name: Manually Dispatch Remote CICD Trigger Event 
      id: manual-devops-wkflow-dispatch
      uses: aurelien-baudet/workflow-dispatch@v2.1.1
      with:
          workflow: '${{ github.event.inputs.data-exchange-hl7-workflow }}'
          repo: cdcent/data-exchange-hl7-devops
          token: ${{ env.access_token }}
          inputs: '{ "targetEnv": "${{ github.event.inputs.targetEnv }}", "commitID": "${{ env.sha }}", "data-exchange-hl7-branch": "${{ github.event.inputs.data-exchange-hl7-branch  }}" }'
          ref: 'main'
          wait-for-completion: true
          wait-for-completion-timeout: 120m
          wait-for-completion-interval: 300s
          display-workflow-run-url: true

    - name: Automatically Dispatch Remote Scan Event 
      uses: aurelien-baudet/workflow-dispatch@v2.1.1
      with:
          workflow: 
          # did not find -> "Fortify Scan on Pull Request to main" 
          # workflow: pull-request-code-scan.yaml # reports not found
          repo: cdcent/data-exchange-hl7-devops
          token: ${{ secrets.CDC_COE_BOTFREY_PEM }}
          inputs: '{ "commitID": "HaHaHaHaHaHaHa" }'
          ref: 'Fix-HL7-Pipeline' # TODO change this to main
          wait-for-completion: true
          wait-for-completion-timeout: 120m
          wait-for-completion-interval: 300s
          display-workflow-run-url: true    
