# Fortify code scan required when merging to Main

name: Code Scan Workflow

defaults:
  run:
    shell: bash

on:
  push: 
    branches: [HL7-2957]
  pull_request:
    branches: [HL7-2957]

  workflow_dispatch:
    inputs:
      # commitID: 
      #   default: "BlahBlah"
      #   type: string
      #   required: false
      data-exchange-hl7-workflow:
        default: 'pull-request-code-scan.yml'
        type: string
        required: false

permissions:
  contents: read
  pull-requests: write # required for `comment-summary-in-pr`
      
jobs:
  path_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0


      # - name: List all changed files
      #   id: updated_dirs
      #   run: |
      #     git diff --name-only ${{ github.event.before }} ${{ github.event.after }}

      - name: List top-level directories with changed files
        id: top_level_dirs
        run: |
          # init assoc. array to store unique dir names
          declare -a unique_dirs

          # Loop over each line ouput from git diff
          while IFS= read -r file; do
            # fetch name of top level directory with changes
            top_dir=$(echo "$file" | cust -d'/' -fi)
            
            # store unique changed dir name
            unique_dirs["$top_dir"]=1

          done <(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})

          echo display list of changed dirs $unique_dirs




  # invoke-manual-code-scan:
  #   runs-on: ubuntu-latest
  #   environment: dev
      
  #   steps:
  #   - name: Gen GitHub App Access Token For Manual Trigger
  #     id: github-app-token
  #     run: |
  #       echo ${{ github.workspace }} 
  #       if [ ! -d data-exchange-hl7 ]; then git clone https://github.com/kave/github-app-token.git; fi;
  #       sudo tree -df
  #       cd github-app-token
  #       sudo gem install jwt
  #       echo "${{ secrets.CDC_COE_BOTFREY_PEM }}" > app-private-key.pem
  #       chmod +x ./get-github-app-access-token.sh;
  #       . ./get-github-app-access-token.sh;
  #       echo "access_token=${TOKEN}" >> "$GITHUB_ENV"
  #   - name: Git Commit SHA
  #     id: getsha
  #     run: | 
  #       echo "sha=${{ inputs.commitID }}" >> "$GITHUB_ENV"
  #   - name: Manually Dispatch Remote CICD Trigger Event 
  #     id: manual-devops-wkflow-dispatch
  #     uses: aurelien-baudet/workflow-dispatch@v2.1.1
  #     with:
  #         workflow: pull-request-code-scan.yml
  #         repo: cdcent/data-exchange-hl7-devops
  #         token: ${{ env.access_token }}
  #         inputs: '{ "commitID": "SOMETHING" }'
  #         ref: 'HL7-2957-PR' # 'main'
  #         wait-for-completion: true
  #         wait-for-completion-timeout: 120m
  #         wait-for-completion-interval: 300s
  #         display-workflow-run-url: true

