name: Trigger HL7 Deploy Workflow

on:
  pull_request:
    branches:
     - 'develop'
     - 'main'
    paths:
    - fns-hl7-pipeline/**
    - mrr/**
    - svc-cloud-transport/**
  push:
    branches:
      - 'develop'
      - '!main'
    paths:
      - fns-hl7-pipeline/**
      - mrr/**
      - svc-cloud-transport/**
  workflow_dispatch:
    inputs:
      data-exchange-hl7-workflow:
        description: 'HL7 application CI/CD workflow that you want to trigger in data-exchange-hl7-devops remote repo to deploy to the development environment'
        required: true
        type: choice
        options:
        - deploy-mmg-based-transformer.yml
        - deploy-mmg-based-transformer.yml
        - deploy-mmg-sql-transformer.yml
        - deploy-receiver-debatcher.yml
        - deploy-redactor.yml
        # These are placeholders - have not been implemented yet
        # - deploy-lake-segs-transformer.yml
        # - deploy-mmg-validator.yml
        # - deploy-hl7-json-lake.yml
        # - deploy-structure-validator.yml
        # - dep-loy-cache-loader.yml
        # - deploy-svc-cloud-transport.yml
jobs:
  invoke-remote-cicd-trigger:
    permissions: write-all
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      cdcent-access-token: ${{ steps.github-app-token.outputs.accesstoken }}
    steps:
      - id: az-login
        name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
      - id: github-app-token
        name: Gen GitHub App Access Token
        run: |
          echo ${{ github.workspace }} 
          if [ ! -d data-exchange-hl7 ]; then git clone https://github.com/kave/github-app-token.git; fi;
          sudo tree -df
          cd github-app-token
          sudo gem install jwt
          echo "${{ secrets.CDC_COE_BOTFREY_PEM }}" > app-private-key.pem
          chmod +x ./get-github-app-access-token.sh;
          . ./get-github-app-access-token.sh;
          echo "access_token=${TOKEN}" >> "$GITHUB_ENV"
      - id: dispatch-devops-wkflow
        name: Dispatch Remote CICD Trigger Event
        uses: actions/github-script@v6
        with:
            github-token: ${{ env.access_token }}
            script: |
                  await github.rest.actions.createWorkflowDispatch({
                    owner: 'cdcent',
                    repo: 'data-exchange-hl7-devops',
                    workflow_id: '${{ github.event.inputs.data-exchange-hl7-workflow }}',
                    ref: 'main'
                  })