name: Trigger HL7 Deploy Workflow

on: [pull_request]

jobs:
  invoke-remote-cicd-trigger:
    permissions: write-all
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      cdcent-access-token: ${{ steps.github-app-token.outputs.accesstoken }}
    steps:
      - id: az-login
        name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
      - id: github-app-token
        name: Gen GitHub App Access Token
        run: |
          echo ${{ github.workspace }} 
          if [ ! -d data-exchange-hl7 ]; then git clone https://github.com/kave/github-app-token.git; fi;
          tree -d /home/runner/work/
          cd github-app-token
          sudo gem install jwt
          echo "${{ secrets.CDC_COE_BOTFREY_PEM }}" > app-private-key.pem
          chmod +x ./get-github-app-access-token.sh;
          . ./get-github-app-access-token.sh;
          echo "access_token=${TOKEN}" >> "$GITHUB_ENV"
      - id: dispatch-devops-wkflow
        name: Dispatch Remote CICD Trigger Event
        uses: actions/github-script@v6
        with:
            github-token: ${{ env.access_token }}
            script: |
                  await github.rest.actions.createWorkflowDispatch({
                    owner: 'cdcent',
                    repo: 'data-exchange-hl7-devops',
                    workflow_id: 'deploy-mmg-based-transformer.yml',
                    ref: 'main'
                  })